

'''
This file contains all the geographic math currently needed for V1 of the flight planning engine.
It is not designed to be knowledgable of ANY aircraft parameters. Just like a mission request
object, geo.py is simply concerned with the ROUTE. For now, the functions here also
assume perfectly legality and other constants according to constants.py.

It contains the following functions (descriptions soon to follow):

        1. normalize_heading(heading_deg)
        2. destination_point(start_lon, start_lat, heading_deg, distance_km)
        3. bearing_between(point A, point B)
        4. distance_between(point A, point B)
        5. make_line_through_point(center_point, heading_deg, length_km)
        6. offset_line(line, offset_heading_deg, offset_km)
        7. make_lawnmower_grid_through_m1()
'''

# IMPORTS:
from pyproj import Geod
from shapely.geometry import Point, LineString
#import math
#from typing import List, Tuple

#CONSTANTS:
#Constants used in this file are global and defined below:
g = Geod(ellps='WGS84')
CONST_360_DEG = 360
CONST_METER_CONVERSION = 1000

'''
FUNCTION: normalize_heading(heading_deg)

DESCRIPTION: This function standarizes heading inputs into the following range:
0 <= heading < 360.
(0 degress is considered equivalent to 360 in this context)
(This effectively makes the range: 0 <= heading <= 359)

PARAMETER(S): heading_deg: a heading value in degress, floats are rejected

RETURNS: heading_deg standardized to the range 0 <= heading < 360 
'''

def normalize_heading(heading_deg):
        
        while isinstance(heading_deg, int) is not True:
                print("Invalid input! Please input an integer!\n")
                heading_deg = int(input("Input an integer heading value: "))

        print("Success!")
        
        if heading_deg < 0:
                print("Heading normalized.")
                return (heading_deg + CONST_360_DEG)
        elif heading_deg > 359:
                print("Heading normalized.")
                return (heading_deg % CONST_360_DEG)
        else:
                print("Heading normalized.")
                return heading_deg
        
#========================================================================================
    
'''
FUNCTION: destination_point(start_point, heading_deg, distance_km)

DESCRIPTION: This function moves in a heading_deg direction for a 
certain distance_km in order to make a destination point. This allows the
UAV to traverse from one waypoint to the next. It is also how a grid with
waypoints is built for the lawnmower pattern. This function is used
to create chains of waypoints that serve as the route for the aircraft.

PARAMETER(S): start_point: a Point object that is the point the destination point will originate from.
              heading_deg: a heading value that is first normalized but then will serve as the heading data for the destination point.
              distance_km: a distance, Units = km, from the start_point that the destination point will be.
              
RETURNS: A Point object that has location and heading data different from start_point.
'''
    
       
def destination_point(start_point, heading_deg, distance_km):
        
        #normalizing the provided heading value 
        # To be used later when output is a waypoint object
        #new_heading = normalize_heading(heading_deg)
        
        # converting provided distance to meters for Geod.fwd()
        distance_in_m = (distance_km * CONST_METER_CONVERSION)
        
        _new_longitude, _new_latitude, back_azimuth = g.fwd(start_point.longitude, start_point.latitude, heading_deg, distance_in_m)
        
        #normalized_heading_to_compare = normalize_heading(heading_to_compare)
        # If the heading generated by g.fwd() is what the user was expecting to use
        # in the new waypoint, use it, if not, override with the user's expected heading.
        #if (new_heading == normalized_heading_to_compare):
        return Point(_new_longitude, _new_latitude)
#========================================================================================